routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes(['verify' => true]);

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('books','BookController');
//Route::get('/search', 'BookController@api')->name('api');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'subtitle', 'isbn13', 'price', 'image', 'url'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/API/BookController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
//use Request;
use GuzzleHttp\Client;
use Illuminate\Database\QueryException;

class BookController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function searchBooks(Request $request)
    {
        $url = 'https://api.itbook.store';
        $client = new Client(['base_uri' => $url]);
        $response = $client->request('GET', '/1.0/search/' . $request->search);
        //echo $response->getBody();
        //$arr = json_decode($response->getBody());
        return($response->getBody());
    }

}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;
//use Request;
use GuzzleHttp\Client;
use Illuminate\Database\QueryException;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //dd($request->input('sort'));
        if($request->has('sort')){
            switch ($request->input('sort')){
                case 'title_asc':
                    $books = Book::orderBy('title')->get();
                    break;
                case 'title_desc':
                    $books = Book::orderByDesc('title')->get();
                    break;
                case 'price_asc':
                    $books = Book::orderBy('price')->get();
                    break;
                case 'price_desc':
                    $books = Book::orderByDesc('price')->get();
                    break;
            }
        }
        else {
            $books = Book::all();
        }


        return view('books.index',compact('books'))
            ->with('i', (request()->input('page', 1) - 1) * 5)
            ->with('sort', $request->input('sort'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $book = (object)['title' => '', 'price' => ''];
        return view('books.search',compact('book'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            Book::create($request->all());
        }
        catch (QueryException $exception){
            $errorCode = $exception->errorInfo[1];
            if($errorCode == 1062){
                return "Duplicate entry '9780071666596' for key 'isbn13'";
            }
        }
        return 'New book added to reading list';
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        return view('books.show',compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->delete();
        return redirect()->route('books.index')
            ->with('success','Book deleted successfully');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Auth\Authenticable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
        $this->middleware(['auth', 'verified']);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }

}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    /**
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('welcome');
    }
}

resources/views/books/create.blade.php
@extends('books.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Book</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('books.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('books.store') }}" method="POST">
        @csrf
        @include('books.form')
    </form>
@endsection

resources/views/books/edit.blade.php
@extends('books.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Book</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('books.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('books.update',$book->id) }}" method="POST">
        @csrf
        @method('PUT')
        <!--
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $book->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail">{{ $book->detail }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        -->
        @include('books.form')
    </form>
@endsection

resources/views/books/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            <input type="text" name="name" value="{{ $book->title }}" class="form-control" placeholder="Title">
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Detail:</strong>
            <input type="text" class="form-control" name="price" placeholder="Price" value="{{ $book->price }}">
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/books/index.blade.php
@extends('books.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Books for reading</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('books.create') }}">Add Book</a>
            </div>
        </div>
    </div>
    <div class="form-group form-inline"style="padding-left: 0px;padding-bottom: 5px; margin-bottom: 0px;">
        <label for="FormControlSelect">Order by:&nbsp;</label>
        <select class="form-control" id="FormControlSelect">
            <option value="">--- Sort order ---</option>
            <option value="title_asc" @if($sort == 'title_asc'){{'selected'}}@endif>Title: Ascending</option>
            <option value="title_desc" @if($sort == 'title_desc'){{'selected'}}@endif>Title: Descending</option>
            <option value="price_asc" @if($sort == 'price_asc'){{'selected'}}@endif>Price: Low to High</option>
            <option value="price_desc" @if($sort == 'price_desc'){{'selected'}}@endif>Price: High to Low</option>
        </select>
    </div>
    <table class="table table-bordered">
        <tr>
            <th width="20px">No</th>
            <th>Title</th>
            <th width="40px">Price</th>
            <th width="180px">Actions</th>
        </tr>
        @foreach ($books as $book)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $book->title }}</td>
                <td>${{ $book->price }}</td>
                <td>
                    <form action="{{ route('books.destroy',$book->id) }}" method="POST" style="margin-block-end: 0em;">
                        <a class="btn btn-info btn-sm" href="{{ route('books.show',$book->id) }}">Details</a>
                        <!--<a class="btn btn-primary" href="{{ route('books.edit',$book->id) }}">Edit</a>-->
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
    <script type="application/javascript">
        $(document).ready(function(){
            if ($('#msg').length)
            {
                $("#msg").delay(5000).fadeOut('slow');
            }
            $("#FormControlSelect").on('change', function(){
                //alert($(this).find('option:selected').val());
                let url = '/books?sort=' + $(this).find('option:selected').val();
                window.location.replace(url);
            });
        });
    </script>
@endsection

resources/views/books/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>My reading list</title>
    <meta name="_token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    @yield('content')
</div>
</body>
</html>

resources/views/books/search.blade.php
@extends('books.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Search books for reading</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('books.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="input-group col-5" style="padding-left: 0px;padding-bottom: 5px;">
        <input type="text" class="form-control" placeholder="Search..." name="search">
        <div class="input-group-append">
            <button type="button" class="btn btn-secondary" id="btn-search">
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
    <div id="pages" style="margin-bottom: 10px; margin-top: 5px;"></div>
    <table class="table table-bordered" id="table">
        <tr>
            <th width="20px">No</th>
            <th>Title</th>
            <th width="40px">Price</th>
            <th width="100px">Action</th>
        </tr>
            <tr>
                <td colspan="4">Fill search field and push "Search" button</td>
            </tr>
    </table>

    <!-- The Modal -->
    <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">The Book</h4>
                    <!-- button type="button" class="close" data-dismiss="modal">&times;</button -->
                </div>

                <!-- Modal body -->
                <div class="modal-body text-center" id="modal-body">
                    <p id="book-name"></p>
                    <p style="color: green; font-weight: bold" id="book-msg">has been added</p>
                </div>
            </div>
        </div>
    </div>
    <div class="overlay"></div>
    <style>
        .overlay{
            display: none;
            position: fixed;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            z-index: 999;
            background: rgba(255,255,255,0.8) url("/images/loader.gif") center no-repeat;
        }
        /*
        body{
            text-align: center;
        }
        */
        /* Turn off scrollbar when body element has the loading class */
        body.loading{
            overflow: hidden;
        }
        /* Make spinner image visible when body element has the loading class */
        body.loading .overlay{
            display: block;
        }
    </style>

    <script type="application/javascript">
        $(document).ready(function(){
            var page = 1;
            // spinner
            $(document).on({
                ajaxStart: function(){
                $("body").addClass("loading");
            },
            ajaxStop: function(){
                $("body").removeClass("loading");
            }
        });
            $(document).on('keypress',function(e) {
                if(e.which == 13) {
                    //alert('You pressed enter!');
                    $('#btn-search').trigger("click");
                }
            });
            function booksSearch(){
                let url;
                url = '/api/search?search=' + $("input[name=search]").val() + '/' + page;
                $.get(url, function(data, status){
                    //alert("Data: " + data + "\nStatus: " + status);
                    let response = JSON.parse(data);
                    page = parseInt(response.page, 10);
                    let pages = Math.ceil(response.total/10);
                    let prev, next = 'active';
                    if(page == 1) prev = 'disabled';
                    if(page == pages) next = 'disabled';
                    let table = '' +
                        '<tr>' +
                        '<th width="20px">No</th>' +
                        '<th>Title</th>' +
                        '<th width="40px">Price</th>' +
                        '<th width="100px">Actions</th>' +
                        '</tr>';
                    $.each(response.books, function(i, item) {
                        table = table + '<tr><td>' + ((page -1)*10 + i + 1) + '</td>';
                        table = table + '<td>' + item.title + '</td>';
                        table = table + '<td>' + item.price + '</td>';
                        table = table + '<td>' + '<button class="btn btn-info btn-sm" id="btn_add_' + i + '">Add</button>' + '</td>';
                        table = table + '</tr>';
                    });
                    $('#pages').html('<b>Page ' + page + ' of ' + pages +
                        '</b> <span style="float: right; font-weight: bold">' +
                        '<nav class="nav" style=" height: 24px">' +
                        '<a id="prev" href="" class="nav-link ' + prev + '" style=" height: 24px; padding: 0rem 1rem;">Previous</a>' +
                        '<a id="next" href="" class="nav-link ' + next +'" style=" height: 24px; padding: 0rem 1rem;">Next</a>' +
                        '</nav></span>');
                    $('#table').html(table);

                    $('[id^=btn_add]').on('click', function(event){
                        event.preventDefault();
                        let i = $(this).attr('id');
                        i = i.substring(8);
                        console.log('i='+i);
                        $.post("/books",
                            {
                                'title': response.books[i].title,
                                'subtitle': response.books[i].subtitle,
                                'price': response.books[i].price.substring(1),
                                '_token': '{{ csrf_token() }}',
                                'isbn13': response.books[i].isbn13,
                                'image': response.books[i].image,
                                'url': response.books[i].url,
                            },
                            function(data, status){
                                //alert(data);
                                $("#book-name").text(response.books[i].title);
                                $("#book-msg").text(data);
                                if(data == 'New book added to reading list'){
                                    $("#book-msg").css("color", "green")
                                    console.log('true-'+data+'-');
                                }
                                else {
                                    $("#book-msg").css("color", "red")
                                    console.log('false-'+data+'-');
                                }
                                $('#myModal').modal('show');
                                setTimeout(function() {$('#myModal').modal('hide');}, 4000);
                            });
                    });
                    $('#prev').on('click', function(e){
                       e.preventDefault();
                       page = page - 1;
                       booksSearch();
                    });
                    $('#next').on('click', function(e){
                        e.preventDefault();
                        page = page + 1;
                        booksSearch();
                    });

                });// end of $.get
            }

            $('#btn-search').on('click', function(){
                page = 1;
                booksSearch();
            });

        });
    </script>
@endsection

resources/views/books/show.blade.php
@extends('books.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Book</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('books.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $book->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Subtitle:</strong>
                {{ $book->subtitle }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Price:</strong>
                {{ $book->price }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>ISBN-13:</strong>
                {{ $book->isbn13 }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>URL:</strong>
                <a href="{{ $book->url }}">{{ $book->url }}</a>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <!--strong>Image:</strong-->
                <img src="{{ $book->image }}">
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>